# MoveIt uses this file to know which ROS 2 controllers to talk to
controller_names:
  - arm_controller

arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: True
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_ee