# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Change the name to something standard and the type to Trajectory
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    # LIST ALL 4 JOINTS HERE
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_ee
    command_interfaces:
      - position
    state_interfaces:
      - position
    # This helps MoveIt stay in sync
    allow_partial_joints_goal: false
    open_loop_control: true