controller_manager:
  ros__parameters:
    update_rate: 100

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Add this block to force the broadcaster to stream at 100fps
joint_state_broadcaster:
  ros__parameters:
    publish_rate: 100.0

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_ee
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints_goal: false
    arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_ee
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints_goal: false